USDA.ARS.GRIN.Web.WebUI/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USDA.ARS.GRIN.Web.Models;
using USDA.ARS.GRIN.Web.WebUI.ViewModels;
using USDA.ARS.GRIN.Web.Repository;

namespace USDA.ARS.GRIN.Web.WebUI.Controllers
{
    public class PagesController : BaseController
    {
        public CollectionRepository _collectionRepository = new CollectionRepository();

        // GET: Pages

        public ActionResult OperatingStatus()
        {
            return View();
        }
        
        public ActionResult Collections()
        {
            CollectionsViewModel viewModel = new CollectionsViewModel();
            viewModel.CollectionSites = _collectionRepository.List();
            return View(viewModel);
        }

        public ActionResult NGRAC()
        {
            return View();
        }

        public ActionResult NMGP()
        {
            return View();
        }

        public ActionResult NGRP()
        {
            return View();
        }

        public ActionResult NGODirectory()
        {
            return View();
        }

        public ActionResult Repositories()
        {
            return View();
        }

        public ActionResult CGC()
        {
            return View();
        }

        public ActionResult GRINU()
        {
            return View();
        }

    }
}

USDA.ARS.GRIN.Web.WebUI/Controllers/RhizobiumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using USDA.ARS.GRIN.Web.Models;
using USDA.ARS.GRIN.Web.WebUI.ViewModels;
using USDA.ARS.GRIN.Web.Repository;
using USDA.ARS.GRIN.Web.Service;

namespace USDA.ARS.GRIN.Web.WebUI.Controllers
{
    public class RhizobiumController : BaseController
    {
        private RhizobiumRepository _repository = new RhizobiumRepository();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(RhizobiumSearchViewModel viewModel)
        {
            Session["RhizobiumSearchResults"] = null;
            viewModel.SearchResults = _repository.Search(viewModel.SearchString);
            Session["RhizobiumSearchResults"] = viewModel.SearchResults;
            return PartialView("~/Views/Rhizobium/_SearchResults.cshtml", viewModel);
        }

        public ActionResult _LeftNavRhizobium()
        {
            List<RhizobiumDescriptor> hostPlants = new List<RhizobiumDescriptor>();

            hostPlants = _repository.GetHostPlants();

            return PartialView(hostPlants);
        }

        public ActionResult Detail(string plantName)
        {
            RhizobiumDetailViewModel viewModel = new RhizobiumDetailViewModel();
            viewModel.HostPlantName = plantName;
            viewModel.RhizobiumDescriptors = _repository.Detail(plantName);
            return PartialView("~/Views/Rhizobium/_Detail.cshtml", viewModel);
        }

        public ActionResult Export()
        {
            return RenderExcel("RhizobiumSearchResults");
        }
       
    }
}

USDA.ARS.GRIN.Web.WebUI/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USDA.ARS.GRIN.Web.WebUI.ViewModels;
using USDA.ARS.GRIN.Web.Repository;
using USDA.ARS.GRIN.Web.Service;

namespace USDA.ARS.GRIN.Web.WebUI.Controllers
{
    public class SearchController : BaseController
    {
        Repository.GRINRepository _repository = new Repository.GRINRepository();

        // GET: Search
        public ActionResult rhizobium()
        {
            RhizobiumSearchViewModel viewModel = new RhizobiumSearchViewModel();
            viewModel.PageAction = "INIT";
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Rhizobium(RhizobiumSearchViewModel viewModel)
        {

            viewModel.SearchResults = _repository.SearchRhizobium(viewModel.SearchString);

            return View(viewModel);
        }
    }
}

USDA.ARS.GRIN.Web.WebUI/Views/Rhizobium/Index.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutV2.cshtml";
}

<div class="usa-overlay"></div>

<style>
    table {
        border: none;
    }

        table th {
            background-color: #0071bc;
            color: white;
        }

        table td {
            background-color: #dfdfdf;
            color: black;
        }
</style>

@Html.Partial("~/Views/Shared/_Banner.cshtml")

<!-- BREADCRUMBS -->
<div class="usda-breadcrumb-with-sidebar">
    <div id="block-usda-breadcrumbs" class="usda-block usda-breadcrumb">
        <nav class="usa-grid" aria-label="Breadcrumb">
            <ol class="usda-breadcrumb-list">
                <li class="usda-breadcrumb-item">
                    <a href="@Url.Action("Index", "Home")" class="no-ext-icon">GRIN Home</a>
                </li>
                <li class="usda-breadcrumb-item">
                    <a href="@Url.Action("Collections","Pages")" class="no-ext-icon">GRIN Collections</a>
                </li>
                <li class="usda-breadcrumb-item">
                    Rhizobium Collection
                </li>
            </ol>
        </nav>
    </div>
</div>

<main id="main-content" class="usa-section usa-content usa-layout-docs with-breadcrumb with-sidebar with-hero">
    <div id="block-usda-page-title" class="usda-block usda-page-title-block usda-page-title-block-with-hero">
        <h1 class="usda-page-title usda-page-title-with-hero"><span class="usda-page-title--main">GRIN </span><span class="usda-page-title--sub">Databases</span><span class="usda-page-title--sub">Rhizobium</span></h1>
    </div>
    <div class="usa-layout-docs-main_content">
        <aside class="usa-layout-docs-sidenav">
            @Html.Partial("~/Views/Shared/_LeftNavSearch.cshtml")
            @{Html.RenderAction("_LeftNavRhizobium", "Rhizobium");}
        </aside>

        <div id="block-usda-content" class="usda-block block-usda-content">
            <h2>Rhizobium Collection</h2>
            <div class="alert alert-primary">
                To request material from the Rhizobium collection, please contact <strong>Patrick Elia</strong> at
                <a href="mailto:​patrick.elia@usda.gov">​patrick.elia@usda.gov</a>
            </div>
            <div id="section-detail">

            </div>
        </div>
    </div>
</main>

USDA.ARS.GRIN.Web.WebUI/Views/Rhizobium/Search.cshtml
@{
    ViewBag.Title = "Rhizobium Collection Advanced Search";
    Layout = "~/Views/Shared/_LayoutV2.cshtml";
}

<script type="text/javascript" src="~/Scripts/Search.js"></script>

<div class="usa-overlay"></div>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/b-1.5.4/b-colvis-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/fh-3.1.4/r-2.2.2/rr-1.2.4/sl-1.2.6/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/b-1.5.4/b-colvis-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/fh-3.1.4/r-2.2.2/rr-1.2.4/sl-1.2.6/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.2.6/js/dataTables.fixedColumns.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<link rel="stylesheet" href="https://gyrocode.github.io/jquery-datatables-checkboxes/1.2.10/css/dataTables.checkboxes.css" />

<style>
    table {
        border: none;
    }

        table th {
            background-color: #0071bc;
            color: white;
        }

        table td {
            background-color: #dfdfdf;
            color: black;
        }
</style>

@Html.Partial("~/Views/Shared/_Banner.cshtml")

<!-- BREADCRUMBS -->
<div class="usda-breadcrumb-with-sidebar">
    <div id="block-usda-breadcrumbs" class="usda-block usda-breadcrumb">
        <nav class="usa-grid" aria-label="Breadcrumb">
            <ol class="usda-breadcrumb-list">
                <li class="usda-breadcrumb-item">
                    <a href="@Url.Action("Index", "Home")" class="no-ext-icon">GRIN Home</a>
                </li>
                <li class="usda-breadcrumb-item">
                    <a href="@Url.Action("Collections","Pages")" class="no-ext-icon">GRIN Collections</a>
                </li>
                <li class="usda-breadcrumb-item">
                    <a href="@Url.Action("Index","Rhizobium")" class="no-ext-icon">Rhizobium Collection</a>
                </li>
                <li class="usda-breadcrumb-item">
                    Rhizobium Advanced Search
                </li>
            </ol>
        </nav>
    </div>
</div>

<main id="main-content" class="usa-section usa-content usa-layout-docs with-breadcrumb with-sidebar with-hero">
    <div id="block-usda-page-title" class="usda-block usda-page-title-block usda-page-title-block-with-hero">
        <h1 class="usda-page-title usda-page-title-with-hero"><span class="usda-page-title--main">GRIN </span><span class="usda-page-title--sub">Collections</span><span class="usda-page-title--sub">Rhizobium</span></h1>
    </div>
    <div class="usa-layout-docs-main_content">
        <aside class="usa-layout-docs-sidenav">
            @Html.Partial("~/Views/Shared/_LeftNavSearch.cshtml")

            <nav id="block-usda-subnavigation" class="usda-block" aria-label="Subnavigation">
                <div id="left-nav-search-results-options" style="display:none;">
                    <ul class="usa-accordion-bordered usa-sidenav-list">
                        <li>
                            <button class="usa-accordion-button" aria-expanded="false" aria-controls="a1"> Page Navigation </button>
                            <div id="a1" class="usa-accordion-content">
                                <a href="#" class="usa-current is-active">Search Results</a>
                                <ul class="usa-sidenav-sub_list">
                                    <li>
                                        <a href="@Url.Action("Export","Rhizobium")">Export to Excel</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

        </aside>
        <div id="block-usda-content" class="usda-block block-usda-content">
            <h2>Rhizobium Advanced Search</h2>
            <!-- "SEARCHING...PLEASE WAIT OVERLAY -->
            <div id="wait" style="display:none;  background-color: black;  position: fixed;  top: 0; right: 0; bottom: 0; left: 0;  opacity: 0.2; /* also -moz-opacity, etc. */  z-index: 10;">
                <img src="~/Images/giphy.gif" style="position: absolute; top: 50%; left: 50%; width: 300px; height: 300px; margin-top: -250px; /* Half the height */  margin-left: -250px; /* Half the width */" />
            </div>

            @using (Html.BeginForm("Search", "Rhizobium", FormMethod.Post, new { id = "frmSearch" }))
            {
                <div class="usa-width-one-whole">

                    <div class="form-group" style="font-size:small;">
                        You may search using any accession identifier, including:
                        <ul>
                            <li>Primary identifier (e.g., 110)</li>
                            <li>Synonyms</li>
                            <li>Host plant scientific name or common name</li>
                        </ul>
                    </div>
                </div>
                <div class="usa-width-one-whole">
                    <div class="usa-width-one-whole">
                        <label for="exampleInputEmail1"><strong>Search Criteria</strong></label>
                        <input type="text" id="txtSearchString" name="SearchString" class="form-control" style="font-size:1.3rem;" aria-describedby="emailHelp" placeholder="Enter search text">                    @*<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>*@
                        <div style="margin-top:15px;">
                            <button id="btnSearch" type="submit" class="btn btn-primary pull-right" style="margin-top:0px;">Search</button>
                            <button id="btnReset" type="button" class="btn btn-danger pull-right" style="margin-top:0px;">Reset</button>
                        </div>

                        <div>
                            <div style="text-align:right; border-bottom:1px solid gray; text-align:right; padding:10px;">

                            </div>
                        </div>
                    </div>
                    <div class="usa-width-one-half">

                    </div>
                </div>

                <div class="usa-width-one-whole">

                </div>
            }

            <div id="search-results-container">

            </div>

        </div>
    </div>
</main>

<script type="text/javascript">
    $('#frmSearch').on('submit', function (evt) {
        evt.preventDefault();

        $.post('Search', $(this).serialize(), function (response) {

            $('#search-results-container').html(response); // assuming response is HTML
        });
        $("#left-nav-search-results-options").show();
    });

    $("#btnReset" ).click(function() {
        $("#txtSearchString").val("");
        $('#search-results-container').html("");
    });

    @*$(".dataset-selector").click(function () {

    var value = $(this).attr("href");
    event.preventDefault();

    var url = '@Url.Action("Detail", "Rhizobium")';

    $.post(url, { plantName: value })
    .done(function (response) {
    $("#section-detail").html(response);
    });
});*@

</script>
<script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

USDA.ARS.GRIN.Web.WebUI/Views/Rhizobium/_Detail.cshtml
@model USDA.ARS.GRIN.Web.WebUI.ViewModels.RhizobiumDetailViewModel
@using (Html.BeginForm("ExportToExcel", "Rhizobium", FormMethod.Post))
{
    <div style="margin-right:0px; margin-top:35px; margin-bottom:0px; padding-right:0px; padding-bottom:5px;">
        <a href="#" style="font-size: 2.50rem; font-weight:bold; text-decoration:none; cursor:none; padding-left:0px; margin-left:0px;">@Model.HostPlantName (@Model.RhizobiumDescriptors.Count)</a>
    </div>

    <div class="search-results-container-grid">
        <table id="example" class="pvp-application-table" style="width:100%; margin-top:0px;">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>USDA Accession</th>
                    <th>Synonym 1</th>
                    <th>Synonym 2</th>
                    <th>Synonym 3</th>
                    <th>Synonym 4</th>
                    <th>Host Plant</th>
                    <th>Common Name</th>
                    <th>Source</th>
                    <th>GEO Source</th>
                    <th>Serogroup</th>
                    <th>Hosts Nodules</th>
                    <th>Comments</th>
                    <th>Genus SPP</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.RhizobiumDescriptors != null)
                {
                    if (Model.RhizobiumDescriptors.Count() > 0)
                    {
                        foreach (var result in Model.RhizobiumDescriptors)
                        {
                    <tr>
                        <td>@result.RhyID</td>
                        <td>@result.USDAAccession</td>
                        <td>@result.Synonym1</td>
                        <td>@result.Synonym2</td>
                        <td>@result.Synonym3</td>
                        <td>@result.Synonym4</td>
                        <td>@result.HostPlant</td>
                        <td>@result.CommonName</td>
                        <td>@result.Source</td>
                        <td>@result.GeoSource</td>
                        <td>@result.SeroGroup</td>
                        <td>@result.HostsNodu</td>
                        <td>@result.Comments</td>
                        <td>@result.GenusSPP</td>
                    </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
}

USDA.ARS.GRIN.Web.WebUI/Views/Rhizobium/_SearchResults.cshtml
@model USDA.ARS.GRIN.Web.WebUI.ViewModels.RhizobiumSearchViewModel
    
<h5 style="padding-bottom:0px;">Search Results: @Model.SearchResults.Count() Records Found</h5>

<input type="hidden" id="hfResultsFound" value="@Model.SearchResults.Count()" />

@using (Html.BeginForm("ExportToExcel", "Rhizobium", FormMethod.Post))
{
    <div class="search-results-container-grid">
        <table id="search-results-table" class="table table-striped table-bordered" style="margin-top:0px; width:100%;">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>USDA Accession</th>
                    <th>Synonym 1</th>
                    <th>Synonym 2</th>
                    <th>Synonym 3</th>
                    <th>Synonym 4</th>
                    <th>Host Plant</th>
                    <th>Common Name</th>
                    <th>Source</th>
                    <th>GEO Source</th>
                    <th>Serogroup</th>
                    <th>Hosts Nodules</th>
                    <th>Comments</th>
                    <th>Genus SPP</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.SearchResults != null)
                {
                    if (Model.SearchResults.Count() > 0)
                    {
                        foreach (var result in Model.SearchResults)
                        {
                            <tr>
                                <td>@result.RhyID</td>
                                <td>@result.USDAAccession</td>
                                <td>@result.Synonym1</td>
                                <td>@result.Synonym2</td>
                                <td>@result.Synonym3</td>
                                <td>@result.Synonym4</td>
                                <td>@result.HostPlant</td>
                                <td>@result.CommonName</td>
                                <td>@result.Source</td>
                                <td>@result.GeoSource</td>
                                <td>@result.SeroGroup</td>
                                <td>@result.HostsNodu</td>
                                <td>@result.Comments</td>
                                <td>@result.GenusSPP</td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
}
<script type="text/javascript">
    $(document).ready( function () {
        $('#search-results-table').DataTable(
        {
            "searching": false,
            "scrollX": true
        });
} );
</script>