USDA.ARS.GRIN.Web.UI.v2/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USDA.ARS.GRIN.Web.DataLayer;
using USDA.ARS.GRIN.Web.ViewModelLayer;
using NLog;

namespace USDA.ARS.GRIN.Web.UI.v2.Controllers
{
    public class ContactController : Controller
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();
        // GET: Contact
        public ActionResult Index()
        {
            TempData["PAGE_CONTEXT"] = "Contact Us";
            ContactViewModel viewModel = new ContactViewModel();
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Send(ContactViewModel viewModel)
        {
            try
            {
                viewModel.SendMessage();
                TempData["PAGE_CONTEXT"] = "Contact Us";
                return View("~/Views/Contact/Confirm.cshtml");
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }
    }
}

USDA.ARS.GRIN.Web.UI.v2/Controllers/PVPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USDA.ARS.GRIN.Web.ViewModelLayer;
using NLog;

namespace USDA.ARS.GRIN.Web.UI.v2.Controllers
{
    public class PVPController : Controller
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();
        // GET: PVP
        public ActionResult Index()
        {
            PVPApplicationViewModel viewModel = new PVPApplicationViewModel();
            TempData["PAGE_CONTEXT"] = "PVP Application Status Database";
            try
            {
                viewModel.SearchEntity.TimeFrame = "REXP";
                viewModel.Search();
                return View(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        public ActionResult Detail(int id)
        {
            PVPApplicationViewModel viewModel = new PVPApplicationViewModel();
            TempData["PAGE_CONTEXT"] = "PVP Application Detail";
            return View(viewModel);
        }

        public ActionResult Search(string status = "")
        {
            TempData["PAGE_CONTEXT"] = "PVP Application Search";
            PVPApplicationViewModel viewModel = new PVPApplicationViewModel();
          
            if (!String.IsNullOrEmpty(status))
            {
                viewModel.SearchEntity.CertificateStatus = status;
                viewModel.SearchEntity.StatusDateRange = "01Y";
                viewModel.Search();
            }
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Search(PVPApplicationViewModel viewModel)
        {
            try
            {
                TempData["PAGE_CONTEXT"] = "PVP Application Search";
                viewModel.Search();
                ModelState.Clear();
                return View(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        public PartialViewResult _List(FormCollection formCollection)
        {
            PVPApplicationViewModel viewModel = new PVPApplicationViewModel();
            TempData["PAGE_CONTEXT"] = "PVP Application Status Database";
            try
            {
                if (!String.IsNullOrEmpty(formCollection["TimeFrame"]))
                {
                    viewModel.SearchEntity.TimeFrame = formCollection["TimeFrame"];
                }

                if (!String.IsNullOrEmpty(formCollection["StatusList"]))
                {
                    viewModel.SearchEntity.CertificateStatusList = formCollection["StatusList"];
                }

                viewModel.Search();
                return PartialView("~/Views/PVP/_List.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        public PartialViewResult _ListTotals()
        {
            PVPApplicationViewModel viewModel = new PVPApplicationViewModel();
            try
            {
                viewModel.GetTotals();
                return PartialView("~/Views/PVP/_ListByStatus.cshtml", viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
    }
}

USDA.ARS.GRIN.Web.UI.v2/Views/PVP/Index.cshtml
@model USDA.ARS.GRIN.Web.ViewModelLayer.PVPApplicationViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUSWDSInterior.cshtml";
}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
<style>
    #overlay {
        height: 100%;
        width: 100%;
        position: fixed; /* NOTE: Had originally been "absolute;" overlay did not conceal entire page and allowed scrolling behind it. */
        top: 0px;
        left: 0px;
        z-index: 99999;
        background-color: #1b1b1b;
        color: white;
        filter: alpha(opacity=75);
        -moz-opacity: 0.75;
        opacity: 0.75;
        display: none;
        overflow: scroll;
    }

        #overlay h2 {
            position: fixed;
            margin-left: 40%;
            top: 40%;
        }

    #section-pvp-data-filters .usa-accordion__button {
        -moz-osx-font-smoothing: inherit;
        -webkit-font-smoothing: inherit;
        border: 0;
        border-radius: 0;
        box-shadow: none;
        padding: 0;
        text-align: left;
        background-image: url(https://designsystem.digital.gov/assets/img/icons/remove.svg),linear-gradient(transparent,transparent);
        background-repeat: no-repeat;
        background-color: #f0f0f0;
        background-position: right 1.25rem center;
        background-size: 1.5rem;
        color: #1b1b1b;
        cursor: pointer;
        display: inline-block;
        font-weight: 700;
        margin: 0;
        padding: 1rem 3.5rem 1rem 1.25rem;
        text-decoration: none;
        width: 100%;
        background-image: url(https://designsystem.digital.gov/assets/img/icons/remove-white.svg),linear-gradient(transparent,transparent);
        background-repeat: no-repeat;
        background-color: #0050d8;
        color: #fff;
    }

        #section-pvp-data-filters .usa-accordion__button:hover {
            background-color: #0050d8;
            color: white;
            border-color: #0050d8;
        }

     
    /*.usa-alert--info .usa-alert__body::before {
        background: url(/assets/img/usa-icons/info.svg) no-repeat center/contain;
        height: 2rem;
        width: 2rem;
        content: "";
        display: block;
        height: 4;
        left: .5rem;
        position: absolute;
        top: .75rem;*/
 
</style>

<div id="overlay"><h2>Loading .. Please wait</h2></div>

<div class="usa-section">
    <div class="grid-container" style="max-width:84rem;">
        <div class="grid-row grid-gap">
            <div class="usa-layout-docs__sidenav desktop:grid-col-2">
                <nav aria-label="Secondary navigation">
                    <ul class="usa-sidenav">
                        <li class="usa-sidenav__item">
                            <a href="@Url.Action("Index","Home")">Home</a>
                        </li>
                        <li class="usa-sidenav__item">
                            <a href="@Url.Action("Index", "Home")" class="usa-current">PVP Applications</a>
                        </li>
                        <li class="usa-current">
                        </li>
                        <li class="usa-sidenav__item">
                            <ul class="usa-sidenav__sublist">
                                <li class="usa-sidenav__item">
                                    <a href="#section-briefings">Browse Applications</a>
                                </li>
                                <li class="usa-sidenav__item">
                                    <a href="@Url.Action("Search","PVP")">Advanced Search</a>
                                </li>
                            </ul>
                        </li>
                        <li class="usa-sidenav__item">
                            <a href="javascript:void(0);">Contact Us</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <main class="usa-layout-docs__main desktop:grid-col-10 usa-prose usa-layout-docs" id="main-content">
                <h2 id="section-heading-h3">Overview</h2>
                <p style="max-width:94rem;">
                    The PVPO provides intellectual property protection to breeders of new
                    varieties of sexually reproduced, tuber propagated, and asexually reproduced plant varieties.
                    In accordance with the <a class="usa-link" href="https://uscode.house.gov/browse/prelim@title7/chapter57/subchapter1&edition=prelim">Plant Variety Protection Act (PVPA)</a>, it examines new varieties, and grants <a class="usa-link" href="https://www.ams.usda.gov/services/plant-variety-protection/issued-certificates">certificates</a> that protect
                    varieties for 20 years (25 years for woody vines and trees).
                </p>
                <div id="section-pvp-data">
                    @*@Html.Partial("~/Views/PVP/_ListByStatus.cshtml")*@
                </div>
                <h3 id="section-heading-h3">Browse Applications</h3>
                <div class="usa-alert usa-alert--info">
                    <div class="usa-alert__body">
                        <p class="usa-alert__text">
                            All data represented here is based on an <a class="usa-link" href="https://www.ams.usda.gov/services/plant-variety-protection/application-status">update</a> from <strong>4/11/2023</strong>. Please <a href="@Url.Action("Index","Contact", new { context="pvp" })">contact us</a> regarding any errors or omissions.
                        </p>
                    </div>
                </div>
                <h4>Certificate Recently Expired (@Model.DataCollection.Count)</h4>
                <table id="data-table_pvp_applications" class="display table-responsive">
                    <thead>
                        <tr>
                            <th>PV Number</th>
                            <th>Applicant</th>
                            <th>Variety (Cultivar)</th>
                            <th>Common Name</th>
                            <th>Experimental Name</th>
                            <th>Expiration Date</th>
                            <th>Accession</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var result in Model.DataCollection)
                        {
                        <tr>
                            <td>@result.ApplicationNumber</td>
                            <td>@result.Applicant</td>
                            <td>@result.VarietyName</td>
                            <td>@result.CommonName</td>
                            <td>@result.ScientificName</td>
                            <td>
                                @if (result.ExpirationDate > DateTime.MinValue)
                                {
                                    @result.ExpirationDate.ToString("yyyy-MM-dd")
                                }
                            </td>
                                                @*<td>
                                @if (!String.IsNullOrEmpty(result.CertificateURL))
                                {
                                    <a href="@result.CertificateURL">
                                        @result.CertificateStatus
                                    </a>
                                }
                                else
                                {
                                    @result.CertificateStatus
                                }
                            </td>*@

                            <td>
                                <a class="usa-link usa-link--alt usa-link--external" href="https://npgsweb.ars-grin.gov/gringlobal/accessiondetail?id=@result.AccessionID">

                                    @result.AccessionName
                                </a>
                            </td>
                            <td>
                                @if (!String.IsNullOrEmpty(result.CertificateURL))
                                {
                                    <a href="@result.CertificateURL">
                                        <img src="~/assets/img/PDF_32.png" />
                                    </a>
                                }
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>




                @*<div id="section-pvp-data-filters" class="usa-accordion">
            <h4 class="usa-accordion__heading">
                <button id="btnExpiring6Months"
                        type="button"
                        title="EXP6"
                        class="usa-accordion__button"
                        aria-expanded="true"
                        aria-controls="section-EXP6">
                    Certificate Expiring in 6 Months
                </button>
            </h4>
            <div id="section-EXP6" class="usa-accordion__content usa-prose">
            </div>
            <h4 class="usa-accordion__heading">
                <button type="button"
                        id="btnRecentlyExpired"
                        title="REXP"
                        class="usa-accordion__button"
                        aria-expanded="false"
                        aria-controls="section-REXP">
                    Certificate Recently Expired
                </button>
            </h4>
            <div id="section-REXP" class="usa-accordion__content usa-prose">
            </div>
            <h4 class="usa-accordion__heading">
                <button type="button"
                        title="RSUB"
                        class="usa-accordion__button"
                        aria-expanded="false"
                        aria-controls="section-RSUB">
                    Application Recently Submitted
                </button>
            </h4>
            <div id="section-RSUB" class="usa-accordion__content usa-prose">
            </div>
        </div>*@
            </main>
        </div>
    </div>
</div>
    <script type="text/javascript">
        $(document).ready(function () {
            InitDataTable("data-table_pvp_applications");
        });
        /* Formatting function for row details - modify as you need */
        //function format(d) {
        //    // `d` is the original data object for the row
        //    return (
        //        '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">' +
        //        '<tr>' +
        //        '<td>Full name:</td>' +
        //        '<td>' +
        //        d.name +
        //        '</td>' +
        //        '</tr>' +
        //        '<tr>' +
        //        '<td>Extension number:</td>' +
        //        '<td>' +
        //        d.extn +
        //        '</td>' +
        //        '</tr>' +
        //        '<tr>' +
        //        '<td>Extra info:</td>' +
        //        '<td>And any further details here (images etc)...</td>' +
        //        '</tr>' +
        //        '</table>'
        //    );
        //}

        //$(document).ready(function () {
        //    var table = $('#example').DataTable({
                 
        //        columns: [
        //            {
        //                className: 'dt-control',
        //                orderable: false,
        //                data: null,
        //                defaultContent: '',
        //            },
        //            { data: 'name' },
        //            { data: 'position' },
        //            { data: 'office' },
        //            { data: 'salary' },
        //        ],
        //        order: [[1, 'asc']],
        //    });

        //    // Add event listener for opening and closing details
        //    $('#example tbody').on('click', 'td.dt-control', function () {
        //        var tr = $(this).closest('tr');
        //        var row = table.row(tr);

        //        if (row.child.isShown()) {
        //            // This row is already open - close it
        //            row.child.hide();
        //            tr.removeClass('shown');
        //        } else {
        //            // Open this row
        //            row.child(format(row.data())).show();
        //            tr.addClass('shown');
        //        }
        //    });
        //});
        

    $(document).ready(function () {
        LoadData("EXP6");
        $("#data-table_pvp_applications_filter").html("<label>Filter Results</label>");
    });

    $(function () {
        $('.usa-button-group__item button').on('click', function () {
            var context = $(this).attr("title");
            $('.usa-button-group__item button').addClass('usa-button--outline');
            $(this).removeClass('usa-button--outline');
            LoadData(context);
        });
    });

    $('.usa-accordion__button').on('click', function () {
        var id = $(this).attr("id");
        var ariaExpanded = $(this).attr("aria-expanded");
        var ariaControls = $(this).attr("aria-controls");
        var context = $(this).attr("title");

        if (ariaExpanded == "false") {
            LoadData(context);
        }
    });

    function LoadData(context)
    {
        $("#overlay").show();
        var link = '@Url.Action("_List", "PVP")';
        var selectedTimeFrame = context;
        var sectionName = "section-" + context;
        var formData = new FormData();
        formData.append("TimeFrame", context);

        $.ajax({
            url: link,
            type: 'POST',
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (response) {
                $("#" + sectionName).html(response);
                /*InitDataTable("data_table_pvp_application");*/
            }
        });
        $("#overlay").hide();
    }
</script>

USDA.ARS.GRIN.Web.UI.v2/Views/PVP/Search.cshtml
@model USDA.ARS.GRIN.Web.ViewModelLayer.PVPApplicationViewModel
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutUSWDSInterior.cshtml";
}

<style>
    #overlay {
        height: 100%;
        width: 100%;
        position: fixed; /* NOTE: Had originally been "absolute;" overlay did not conceal entire page and allowed scrolling behind it. */
        top: 0px;
        left: 0px;
        z-index: 99999;
        background-color: #1b1b1b;
        color: white;
        filter: alpha(opacity=75);
        -moz-opacity: 0.75;
        opacity: 0.75;
        display: none;
        overflow: scroll;
    }

    #overlay h2 {
        position: fixed;
        margin-left: 40%;
        top: 40%;
    }

    .usa-breadcrumb {
        padding-bottom: 1rem;
        padding-top: 0rem; 
    }
    #section-pvp-search-criteria .usa-accordion__button {
        -moz-osx-font-smoothing: inherit;
        -webkit-font-smoothing: inherit;
        border: 0;
        border-radius: 0;
        box-shadow: none;
        padding: 0;
        text-align: left;
        background-image: url(https://designsystem.digital.gov/assets/img/icons/remove.svg),linear-gradient(transparent,transparent);
        background-repeat: no-repeat;
        background-color: #f0f0f0;
        background-position: right 1.25rem center;
        background-size: 1.5rem;
        color: #1b1b1b;
        cursor: pointer;
        display: inline-block;
        font-weight: 700;
        margin: 0;
        padding: 1rem 3.5rem 1rem 1.25rem;
        text-decoration: none;
        width: 100%;
        background-image: url(https://designsystem.digital.gov/assets/img/icons/remove-white.svg),linear-gradient(transparent,transparent);
        background-repeat: no-repeat;
        background-color: #0050d8;
        color: #fff;
    }

        #section-pvp-search-criteria .usa-accordion__button:hover {
            background-color: #0050d8;
            color: white;
            border-color: #0050d8;
        }
    .usa-alert--info .usa-alert__body::before {
        background: url(/assets/img/usa-icons/info.svg) no-repeat center/contain;
        height: 2rem;
        width: 2rem;
        content: "";
        display: block;
        height: 4;
        left: .5rem;
        position: absolute;
        top: .75rem;
</style>

<div id="overlay"><h2>Loading .. Please wait</h2></div>
<div class="usa-section">
    <div class="grid-container" style="max-width:94rem;">
        <div class="grid-row grid-gap">
            <div class="usa-layout-docs__sidenav desktop:grid-col-2" style="background-color: #f0f0f0; ">
                <nav aria-label="Secondary navigation">
                    <h4>Search Criteria</h4>
                    @using (Html.BeginForm("Search", "PVP", FormMethod.Post, new { id = "frmMain" }))
                    {
                <div id="section-search-criteria" class="margin-top-3">
                    <label class="usa-label" for="SearchEntity_StatusDateRange">Status</label>
                    @Html.DropDownListFor(x => x.SearchEntity.StatusDateRange, Model.StatusDateRanges, new { @class = "usa-select" })
                    <label class="usa-label" for="SearchEntity_CertificateStatus">Status</label>
                    @Html.DropDownListFor(x => x.SearchEntity.CertificateStatus, Model.CertificateStatuses, "All Statuses", new { @class = "usa-select" })
                    <label class="usa-label" for="SearchEntity_Variety">Variety</label>
                    @Html.TextBoxFor(x => x.SearchEntity.Variety, new { @class = "usa-input" })
                    @*<label class="usa-label">Crop Common Name</label>
                    @Html.TextBoxFor(x => x.SearchEntity.CommonName, new { @class = "usa-input" })*@
                    <label class="usa-label">Applicant</label>
                    @Html.TextBoxFor(x => x.SearchEntity.Applicant, new { @class = "usa-input" })
                    <label class="usa-label">Scientific Name</label>
                    @Html.TextBoxFor(x => x.SearchEntity.ScientificName, new { @class = "usa-input" })
                    <label class="usa-label">Experimental Name</label>
                    @Html.TextBoxFor(x => x.SearchEntity.ExperimentalName, new { @class = "usa-input" })
                </div>
                        <ul class="usa-button-group margin-top-2 margin-bottom-2">
                            <li class="usa-button-group__item">
                                <button id="btnReset" type="button" class="usa-button usa-button--outline">Reset</button>
                            </li>
                            <li class="usa-button-group__item">
                                <button id="btnSearch" type="submit" class="usa-button">Search</button>
                            </li>
                        </ul>
                    }
                </nav>
            </div>
            <main class="usa-layout-docs__main desktop:grid-col-10 usa-prose usa-layout-docs" id="main-content">
                <h2 id="section-heading-h2">Advanced Search</h2>
                <a href="@Url.Action("Index","PVP")">Return to PVP Page</a>
                <div class="usa-alert usa-alert--info">
                    <div class="usa-alert__body">
                        <p class="usa-alert__text">
                            All data represented here is based on an <a class="usa-link" href="https://www.ams.usda.gov/services/plant-variety-protection/application-status">update</a> from <strong>1/9/2023</strong>. Please <a href="@Url.Action("Index","Contact", new { context="pvp" })">contact us</a> regarding any errors or omissions.
                        </p>
                    </div>
                </div>
                <h3 id="section-heading-h3">Search Results (@Model.RowsAffected)</h3>
                <table id="data-table_pvp_applications" class="display table-responsive">
                    <thead>
                        <tr>
                            <th>PV Number</th>
                            <th>Applicant</th>
                            <th>Variety (Cultivar)</th>
                            <th>Common Name</th>
                            <th>Experimental Name</th>
                            <th>Expiration Date</th>
                            <th>Status</th>
                            <th></th>
                            <th>Accession</th>
                            @*<th></th>*@
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var result in Model.DataCollection)
                        {
                            <tr>
                                <td>@result.ApplicationNumber</td>
                                <td>@result.Applicant</td>
                                <td>@result.VarietyName</td>
                                <td>@result.CommonName</td>
                                <td>@result.ScientificName</td>
                                <td>
                                    @if (result.ExpirationDate > DateTime.MinValue)
                                    {
                                        @result.ExpirationDate.ToShortDateString()
                                    }
                                </td>
                                <td>
                                    @if (!String.IsNullOrEmpty(result.CertificateURL))
                                    {
                                        <a href="@result.CertificateURL">
                                            @result.CertificateStatus
                                        </a>
                                    }
                                    else
                                    {
                                        @result.CertificateStatus
                                    }
                                </td>
                                <td>
                                    @if (!String.IsNullOrEmpty(result.CertificateURL))
                                    {
                                        <a href="@result.CertificateURL">
                                            <img src="~/assets/img/PDF_32.png" />
                                        </a>
                                    }
                                </td>
                                <td>
                                    <a class="usa-link usa-link--alt usa-link--external" href="https://npgsweb.ars-grin.gov/gringlobal/accessiondetail?id=@result.AccessionID">

                                        @result.AccessionName
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="grid-container margin-top-5" style="max-width:94rem;">
                    <div class="grid-row grid-gap">
                        <div class="grid-col-12">
                            <div id="section-pvp-applications">

                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        </div>
    </div>
<script type="text/javascript">
    $(document).ready(function () {
        InitDataTable("data-table_pvp_applications");
    });

    /* DETAIL */
    $(function () {
        $('.detail-expand').on('click', function () {
            var id = this.id;
            $("#modal-pvp-detail").modal("show");
        });
    });

    /* ========================================================================================
 * Search logic
  ======================================================================================== */
    $(document).on("click", "[id='btnReset']", function () {
        Reset();
    });

    /* If the user resets the search, 1) Remove all search criteria, and 2) Clear the search-results
     * Datatable.*/
    function Reset() {
        $(this).closest('form').find("input[type=text], textarea").val("");
        $("#section-search-criteria select").val("");
        $("#section-search-criteria input[type=text]").val("");
        $("#ItemIDList").val("");
        $("#EventValue").val("");

        // Set date-range to default, rather than clearing it entirely.
        // 01Y
        $("#SearchEntity_StatusDateRange").val("01Y");

        // Operates on all tables on the page.
        $.fn.dataTable
            .tables({ visible: true, api: true })
            .clear()
            .draw();
    }
</script>

USDA.ARS.GRIN.Web.UI.v2/Views/PVP/_List.cshtml
@model USDA.ARS.GRIN.Web.ViewModelLayer.PVPApplicationViewModel

USDA.ARS.GRIN.Web.UI.v2/Views/PVP/_ListByStatus.cshtml
@model USDA.ARS.GRIN.Web.ViewModelLayer.PVPApplicationViewModel
<h3 id="section-heading-h3">Applications by Status (@DateTime.Now.Year)</h3>
<p>
    <table class="usa-table usa-table--borderless" style="width:100%;">
        <thead>
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Description</th>
                <th scope="col">Application Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var result in Model.DataCollectionTotals)
            { 
            <tr>
                <th scope="row"><strong><a href="@Url.Action("Search","PVP", new { status = result.CodeTitle })" style="color:#005ea2;">@result.CodeTitle</a></strong></th>
                <td>
                    @result.CodeDescription
                </td>
                <td>@result.Value</td>
            </tr>       
            }
        </tbody>
    </table>
</p>