USDA.ARS.GRIN.Web.UI.v2/Controllers/CGCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USDA.ARS.GRIN.Web.DataLayer;
using USDA.ARS.GRIN.Web.ViewModelLayer;
using NLog;

namespace USDA.ARS.GRIN.Web.UI.v2.Controllers
{
    public class CGCController : Controller
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();
        // GET: CGC
        public ActionResult Index()
        {
            try 
            { 
                CropGermplasmCommitteeViewModel viewModel = new CropGermplasmCommitteeViewModel();
                TempData["PAGE_CONTEXT"] = "Crop Germplasm Committees";
                return View();
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }

        public PartialViewResult _List()
        {
            try
            {
                CropGermplasmCommitteeViewModel viewModel = new CropGermplasmCommitteeViewModel();
                viewModel.Search();
                return PartialView(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }

        public PartialViewResult _ListDocuments(int cropGermplasmCommitteeId = 0, string categoryCode = "")
        {
            try
            {
                CropGermplasmCommitteeDocumentViewModel viewModel = new CropGermplasmCommitteeDocumentViewModel();
                viewModel.SearchEntity.CropGermplasmCommitteeID = cropGermplasmCommitteeId;
                viewModel.SearchEntity.CategoryCode = categoryCode;
                viewModel.Search();
                return PartialView(viewModel);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return PartialView("~/Views/Error/_InternalServerError.cshtml");
            }
        }
    }
}

USDA.ARS.GRIN.Web.UI.v2/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using USDA.ARS.GRIN.Web.DataLayer;
using USDA.ARS.GRIN.Web.ViewModelLayer;
using NLog;

namespace USDA.ARS.GRIN.Web.UI.v2.Controllers
{
    public class ContactController : Controller
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();
        // GET: Contact
        public ActionResult Index()
        {
            TempData["PAGE_CONTEXT"] = "Contact Us";
            ContactViewModel viewModel = new ContactViewModel();
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Send(ContactViewModel viewModel)
        {
            try
            {
                viewModel.SendMessage();
                TempData["PAGE_CONTEXT"] = "Contact Us";
                return View("~/Views/Contact/Confirm.cshtml");
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                return RedirectToAction("InternalServerError", "Error");
            }
        }
    }
}

USDA.ARS.GRIN.Web.UI.v2/Views/CGC/Index.cshtml
@model USDA.ARS.GRIN.Web.ViewModelLayer.CropGermplasmCommitteeViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUSWDSInterior.cshtml";
}
<link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/main.min.css' rel='stylesheet' />
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/main.min.js'></script>

<div class="usa-section">
    <div class="grid-container">
        <div class="grid-row grid-gap">
            <div class="usa-layout-docs__sidenav desktop:grid-col-2">
                <nav aria-label="Secondary navigation">
                    <ul class="usa-sidenav">
                        <li class="usa-sidenav__item"><a href="">Home</a></li>
                        <li class="usa-sidenav__item">
                            <a href="" class="usa-current">CGC</a>
                            <ul class="usa-sidenav__sublist">
                                <li class="usa-sidenav__item"><a href="#overview">Overview</a></li>
                                <li class="usa-sidenav__item"><a href="#committees">Committees</a></li>
                                <li class="usa-sidenav__item"><a href="#briefings">Chair Briefings</a></li>
                            </ul>
                        </li>
                        <li class="usa-sidenav__item"><a href="@Url.Action("Index", "Contact")">Contact Us</a></li>
                    </ul>
                </nav>
            </div>
            <main class="usa-layout-docs__main desktop:grid-col-10 usa-prose usa-layout-docs" id="main-content">
                <h1>Crop Germplasm Committees (CGC)</h1>
                <p class="usa-intro">
                    The Crop Germplasm Committees are comprised of a cross section of NPGS users who provide technical support to NPGS genebanks
                    and collections.
                </p>
                <a id="overview"></a>
                <h2 id="section-heading-h2">Overview</h2>
                <p>
                    Crop Germplasm Committees (CGC) serve as subject matter experts to guide curatorial staff on best practices, including the priorities and techniques for characterizing the collections. They also help review proposals that fund plant explorations and evaluation grants for scientific rigor.
                </p>
                <p>
                    There are currently <a href="#section-directory">44 CGCs</a> representing almost all major and minor crops of economic importance in the U.S. Each committee includes a chair and members from government agencies, universities, and commercial interests who volunteer their time and expertise to support the NPGS.
                </p>
                <h3 id="section-heading-h3">Documents</h3>
                <table class="usa-table usa-table--borderless usa-table--striped">
                    <thead>
                        <tr>
                            <th scope="col">Document title</th>
                            <th scope="col">Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <a href="https://www.ars-grin.gov/npgs/cgc_reports/2019_CGC_Roles_and_Responsibilities_26_July_2019.doc">
                                    Roles and Responsibilities
                                </a>
                            </th>
                            <td>
                                Additional information about CGC organization and function.
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <a href="https://www.ars-grin.gov/npgs/cgc_reports/Crop_Vulnerability_Statement_Outline.doc">
                                    Crop Vulnerability Statement Outline
                                </a>
                            </th>
                            <td>
                                A guide to the format and content of Crop Vulnerability Statements.
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">
                                <a href="https://www.ars-grin.gov/npgs/cgc_reports/PGR Success Story Fillable Form 4.18.22.docx">
                                    Success Story Template
                                </a>
                            </th>
                            <td>
                                A template for sharing a Success Story resulting from the utilization of Plant Genetic Resources.
                            </td>
                        </tr>
                        <!--TODO-->
                        

                    </tbody>
                </table>
                <a id="committees"></a>
                <h3 id="section-heading-h3TEST">Committees</h3>
                @{ Html.RenderAction("_List", "CGC"); }
                <h3 id="section-heading-h3TEST2">Annual CGC Chair Briefings</h3>
                <a id="briefings"></a>
                @{ Html.RenderAction("_ListDocuments", "CGC", new { @categoryCode = "BRF" }); }            
            </main>
        </div>
    </div>
</div>

<!--<div class="grid-container">
    <div class="grid-row grid-gap">
        <div class="usa-layout-docs__sidenav desktop:grid-col-2">
            <nav aria-label="Secondary navigation">
                <form class="usa-search usa-search--small" role="search">
                    <label class="usa-sr-only" for="search-field-en-small">Search</label>
                    <input class="usa-input" id="search-field-en-small" type="search" name="search" placeholder="Search GRIN-Global">
                    <button class="usa-button" type="submit">
                        <span class="usa-sr-only">Search</span>
                    </button>
                </form>
                <br />
                <ul class="usa-sidenav">
                    <li class="usa-sidenav__item">
                        <a href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li class="usa-sidenav__item">
                        <ul class="usa-sidenav__sublist">
                            <li class="usa-sidenav__item active">
                                <a href="#section-overview">Overview</a>
                            </li>
                            <li class="usa-sidenav__item">
                                <a href="#section-directory">CGC Directory</a>
                            </li>
                            <li class="usa-sidenav__item">
                                <a href="#section-briefings">Annual CGC Chair Briefings</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
        <main class="usa-layout-docs__main desktop:grid-col-10 usa-prose usa-layout-docs" id="main-content">-->
            @*<h1>Crop Germplasm Committees</h1>*@
            <!--<p class="usa-intro">
                The Crop Germplasm Committees (CGC) are comprised of a cross section of NPGS users who provide technical support to NPGS genebanks
                and collections.
            </p>
            <h2 id="section-overview">Overview</h2>
            <p>
                Crop Germplasm Committees (CGC) serve as subject matter experts to guide curatorial staff on best practices, including the priorities and techniques for characterizing the collections. They also help review proposals that fund plant explorations and evaluation grants for scientific rigor.
            </p>
            <p>
                There are currently <a href="#section-directory">44 CGCs</a> representing almost all major and minor crops of economic importance in the U.S. Each committee includes a chair and members from government agencies, universities, and commercial interests who volunteer their time and expertise to support the NPGS.
            </p>

            <table class="usa-table usa-table--borderless usa-table--striped">
                <caption>
                    Introductory Documents
                </caption>
                <thead>
                    <tr>
                        <th scope="col">Document title</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">
                            <a href="https://www.ars-grin.gov/npgs/cgc_reports/2019_CGC_Roles_and_Responsibilities_26_July_2019.doc">
                                Roles and Responsibilities
                            </a>
                        </th>
                        <td>
                            Additional information about CGC organization and function.
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            <a href="https://www.ars-grin.gov/npgs/cgc_reports/Crop_Vulnerability_Statement_Outline.doc">
                                Crop Vulnerability Statement Outline
                            </a>
                        </th>
                        <td>
                            A guide to the format and content of Crop Vulnerability Statements.
                        </td>
                    </tr>
                </tbody>
            </table>

            <h2 id="section-directory">Committees</h2>
            @{ Html.RenderAction("_List", "CGC"); }

            <h2 id="section-briefings">Annual CGC Chair Briefings</h2>
            <table id="data-table-documents-briefings" class="usa-table usa-table--borderless usa-table--striped">
                <caption>
                    CAPTION HERE
                </caption>
                <thead>
                    <tr>
                        <th scope="col">Document title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Year</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Declaration of Independence</th>
                        <td>
                            Statement adopted by the Continental Congress declaring independence
                            from the British Empire.
                        </td>
                        <td>1776</td>
                    </tr>
                    <tr>
                        <th scope="row">Bill of Rights</th>
                        <td>
                            The first ten amendments of the U.S. Constitution guaranteeing rights
                            and freedoms.
                        </td>
                        <td>1791</td>
                    </tr>
                    <tr>
                        <th scope="row">Declaration of Sentiments</th>
                        <td>
                            A document written during the Seneca Falls Convention outlining the
                            rights that American women should be entitled to as citizens.
                        </td>
                        <td>1848</td>
                    </tr>
                    <tr>
                        <th scope="row">Emancipation Proclamation</th>
                        <td>
                            An executive order granting freedom to slaves in designated southern
                            states.
                        </td>
                        <td>1863</td>
                    </tr>
                </tbody>
            </table>

        </main>
    </div>
</div>-->
<script type="text/javascript">
    //InitDataTable("tblDemo");
    //function InitDataTable(tableName) {
    //    $(document).ready(function () {
    //        var table = $("#" + tableName).DataTable({
    //            dom: 'Blfrtip',
    //            paging: true,
    //            //initComplete: function () {
    //            //    SetControlVisibility(tableName);
    //            //},
    //            responsive: true,
    //            buttons: [
    //                'selectAll',
    //                'selectNone',
    //                'csv',
    //                'excel',
    //                'pdf'
    //            ],
    //            select: true,
    //            searching: false,
    //            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
    //            columnDefs: [
    //                { targets: [0], visible: false }
    //            ]
    //        });
    //    });
    //}
</script>

USDA.ARS.GRIN.Web.UI.v2/Views/CGC/_CommitteeList.cshtml
<div class="usa-accordion usa-accordion--bordered" aria-multiselectable="true">

    <!-- Use the accurate heading level to maintain the document outline -->
    <h4 class="usa-accordion__heading">
        <button class="usa-accordion__button"
                aria-expanded="true"
                aria-controls="m-a1">
            Committee Name Here
        </button>
    </h4>
    <div id="m-a1" class="usa-accordion__content usa-prose">
        <div class="usa-table-container--scrollable" tabindex="0">
            <label for="table">Committee Roster</label>
            <div class="usa-table-container--scrollable" tabindex="0">
                <table class="usa-table usa-table--striped">
                    <caption>Scrollable table with horizontal stripes</caption>
                    <col>
                    <colgroup span="2"></colgroup>
                    <colgroup span="2"></colgroup>
                    <thead>
                        <tr>
                            <th rowspan="2">Federal Budget<br> Baseline Projections</th>
                            <th colspan="2" scope="colgroup" class="text-center">2017</th>
                            <th colspan="2" scope="colgroup" class="text-center">2018</th>
                            <th colspan="2" scope="colgroup" class="text-center">2019</th>
                            <th colspan="2" scope="colgroup" class="text-center">2020</th>
                            <th colspan="2" scope="colgroup" class="text-center">2021</th>
                            <th colspan="2" scope="colgroup" class="text-center">Hist. Avg.</th>
                        </tr>
                        <tr>
                            <th scope="col" class="text-right">%GDP</th>
                            <th scope="col" class="text-right">USD*</th>
                            <th scope="col" class="text-right">%GDP</th>
                            <th scope="col" class="text-right">USD*</th>
                            <th scope="col" class="text-right">%GDP</th>
                            <th scope="col" class="text-right">USD*</th>
                            <th scope="col" class="text-right">%GDP</th>
                            <th scope="col" class="text-right">USD*</th>
                            <th scope="col" class="text-right">%GDP</th>
                            <th scope="col" class="text-right">USD*</th>
                            <th scope="col" class="text-right">%GDP</th>
                            <th scope="col" class="text-right">USD*</th>
                        </tr>
                    </thead>
                    <tr>
                        <th scope="row">Revenue</th>
                        <td class="font-mono-sm text-tabular text-right">17.2%</td>
                        <td class="font-mono-sm text-tabular text-right">3,316</td>
                        <td class="font-mono-sm text-tabular text-right">16.4%</td>
                        <td class="font-mono-sm text-tabular text-right">3,338</td>
                        <td class="font-mono-sm text-tabular text-right">16.3%</td>
                        <td class="font-mono-sm text-tabular text-right">3,490</td>
                        <td class="font-mono-sm text-tabular text-right">16.7%</td>
                        <td class="font-mono-sm text-tabular text-right">3,678</td>
                        <td class="font-mono-sm text-tabular text-right">16.7%</td>
                        <td class="font-mono-sm text-tabular text-right">3,827</td>
                        <td class="font-mono-sm text-tabular text-right">17.4%</td>
                        <td class="font-mono-sm text-tabular text-right">3,381</td>
                    </tr>
                    <tr>
                        <th scope="row">Outlays</th>
                        <td class="font-mono-sm text-tabular text-right">20.6%</td>
                        <td class="font-mono-sm text-tabular text-right">3,982</td>
                        <td class="font-mono-sm text-tabular text-right">20.2%</td>
                        <td class="font-mono-sm text-tabular text-right">4,142</td>
                        <td class="font-mono-sm text-tabular text-right">21.0%</td>
                        <td class="font-mono-sm text-tabular text-right">4,470</td>
                        <td class="font-mono-sm text-tabular text-right">21.3%</td>
                        <td class="font-mono-sm text-tabular text-right">4,685</td>
                        <td class="font-mono-sm text-tabular text-right">21.6%</td>
                        <td class="font-mono-sm text-tabular text-right">4,949</td>
                        <td class="font-mono-sm text-tabular text-right">20.3%</td>
                        <td class="font-mono-sm text-tabular text-right">4,198</td>
                    </tr>
                    <tr>
                        <th scope="row">Budget Deficit</th>
                        <td class="font-mono-sm text-tabular text-right">-3.5%</td>
                        <td class="font-mono-sm text-tabular text-right">-665</td>
                        <td class="font-mono-sm text-tabular text-right">-3.8%</td>
                        <td class="font-mono-sm text-tabular text-right">-804</td>
                        <td class="font-mono-sm text-tabular text-right">-4.6%</td>
                        <td class="font-mono-sm text-tabular text-right">-981</td>
                        <td class="font-mono-sm text-tabular text-right">-4.6%</td>
                        <td class="font-mono-sm text-tabular text-right">-1,008</td>
                        <td class="font-mono-sm text-tabular text-right">-4.9%</td>
                        <td class="font-mono-sm text-tabular text-right">-1,123</td>
                        <td class="font-mono-sm text-tabular text-right">-2.9%</td>
                        <td class="font-mono-sm text-tabular text-right">-483</td>
                    </tr>
                    <tr>
                        <th scope="row">Debt Held by Public</th>
                        <td class="font-mono-sm text-tabular text-right">76.0%</td>
                        <td class="font-mono-sm text-tabular text-right">14,665</td>
                        <td class="font-mono-sm text-tabular text-right">77.4%</td>
                        <td class="font-mono-sm text-tabular text-right">15,688</td>
                        <td class="font-mono-sm text-tabular text-right">79.2%</td>
                        <td class="font-mono-sm text-tabular text-right">16,762</td>
                        <td class="font-mono-sm text-tabular text-right">80.9%</td>
                        <td class="font-mono-sm text-tabular text-right">17,872</td>
                        <td class="font-mono-sm text-tabular text-right">83.1%</td>
                        <td class="font-mono-sm text-tabular text-right">18,998</td>
                        <td class="font-mono-sm text-tabular text-right">41.7%</td>
                        <td class="font-mono-sm text-tabular text-right">8,065</td>
                    </tr>
                </table>
            </div>


            <label>Documents</label>
            <table class="usa-table usa-table--borderless">
                <caption>Borderless table: A borderless table can be useful when you want the information to feel more a part of the text it accompanies and extends.</caption>
                <thead>
                    <tr>
                        <th scope="col">Document title</th>
                        <th scope="col">Year</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Declaration of Independence</th>
                        <td>1776</td>
                    </tr>
                   
                   
                </tbody>
            </table>
        </div>
    </div>

    <!-- Use the accurate heading level to maintain the document outline -->
    <h4 class="usa-accordion__heading">
        <button class="usa-accordion__button"
                aria-expanded="false"
                aria-controls="m-a2">
            Second Amendment
        </button>
    </h4>
    <div id="m-a2" class="usa-accordion__content usa-prose">
        <p>A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.</p> <ul><li>This is a list item</li><li>Another list item</li></ul>

    </div>

    <!-- Use the accurate heading level to maintain the document outline -->
    <h4 class="usa-accordion__heading">
        <button class="usa-accordion__button"
                aria-expanded="false"
                aria-controls="m-a3">
            Third Amendment
        </button>
    </h4>
    <div id="m-a3" class="usa-accordion__content usa-prose">
        <p>No Soldier shall, in time of peace be quartered in any house, without the consent of the Owner, nor in time of war, but in a manner to be prescribed by law.</p>

    </div>

    <!-- Use the accurate heading level to maintain the document outline -->
    <h4 class="usa-accordion__heading">
        <button class="usa-accordion__button"
                aria-expanded="false"
                aria-controls="m-a4">
            Fourth Amendment
        </button>
    </h4>
    <div id="m-a4" class="usa-accordion__content usa-prose">
        <p>The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.</p>

    </div>

    <!-- Use the accurate heading level to maintain the document outline -->
    <h4 class="usa-accordion__heading">
        <button class="usa-accordion__button"
                aria-expanded="false"
                aria-controls="m-a5">
            Fifth Amendment
        </button>
    </h4>
    <div id="m-a5" class="usa-accordion__content usa-prose">
        <p>No person shall be held to answer for a capital, or otherwise infamous crime, unless on a presentment or indictment of a Grand Jury, except in cases arising in the land or naval forces, or in the Militia, when in actual service in time of War or public danger; nor shall any person be subject for the same offence to be twice put in jeopardy of life or limb; nor shall be compelled in any criminal case to be a witness against himself, nor be deprived of life, liberty, or property, without due process of law; nor shall private property be taken for public use, without just compensation.</p>

    </div>

</div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.usa-table').DataTable({
                "searching": false
            });
    });
</script>

USDA.ARS.GRIN.Web.UI.v2/Views/CGC/_List.cshtml
@model USDA.ARS.GRIN.Web.ViewModelLayer.CropGermplasmCommitteeViewModel
<div id="section-committees" class="usa-accordion--bordered" style="margin-top:15px;">

    <button id="bookmarkme" type="button">bookmark me!</button>

    @foreach (var result in Model.DataCollection)
    {
        <a id="@result.Name"></a>
        
        <h4 class="usa-accordion__heading">
            <button type="button"
                    class="usa-accordion__button"
                    aria-expanded="false"
                    aria-controls="@result.ID">
                @result.Name
            </button>
        </h4>
        <div id="@result.ID" class="usa-accordion__content usa-prose">
            <p>
                <a href="@result.RosterURL" class="usa-link">Committee Roster</a>
            </p>
            @{Html.RenderAction("_ListDocuments", "CGC", new { cropGermplasmCommitteeId = result.ID });}
            @*<h4>Crop Descriptors</h4>
                <ul class="usa-collection__meta" aria-label="Topics">
                    <li class="usa-collection__meta-item usa-tag">Quarterly update</li>
                    <li class="usa-collection__meta-item usa-tag">CAP goal</li>
                    <li class="usa-collection__meta-item usa-tag">APG</li>
                    <li class="usa-collection__meta-item usa-tag">PMA</li>
                    <li class="usa-collection__meta-item usa-tag">Success story</li>
                </ul>*@

        </div>
    }
</div>
<script type="text/javascript">
    //$(document).ready(function () {
    //    $('.usa-table').DataTable({
    //        "searching": false
    //    });
    //});

    $(document).on("click", "[id='btnSearch']", function () {
        event.preventDefault();
        alert("DEBUG SEARCH CGC");
    });

    $(function () {
        $('#bookmarkme').click(function () {
            if (window.sidebar && window.sidebar.addPanel) { // Mozilla Firefox Bookmark
                window.sidebar.addPanel(document.title, window.location.href, '');
            } else if (window.external && ('AddFavorite' in window.external)) { // IE Favorite
                window.external.AddFavorite(location.href, document.title);
            } else if (window.opera && window.print) { // Opera Hotlist
                this.title = document.title;
                return true;
            } else { // webkit - safari/chrome
                alert('Press ' + (navigator.userAgent.toLowerCase().indexOf('mac') != - 1 ? 'Command/Cmd' : 'CTRL') + ' + D to bookmark this page.');
            }
        });
    });

</script>

USDA.ARS.GRIN.Web.UI.v2/Views/CGC/_ListDocuments.cshtml
@model USDA.ARS.GRIN.Web.ViewModelLayer.CropGermplasmCommitteeDocumentViewModel
<table class="usa-table usa-table--borderless usa-table--striped" style="width:100%;">
    @*<caption>
            Introductory Documents
        </caption>*@
    <thead>
        <tr>
            <th scope="col">Document title</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var result in Model.DataCollection)
        { 
            <tr>
                <th scope="row">
                    <a href="@result.URL">
                        @result.Title
                    </a>
                </th>
            </tr>        
        }
    </tbody>
</table>